# Generated by Django 4.0 on 2022-01-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municaplities', '0005_remove_district_id_remove_municipalities_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='municipalities',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='uuid',
            new_name='id',
        ),
    ]
